-- Hobby Bento prototype schema.
-- SECURITY NOTE: this v1 intentionally allows anonymous browser users to read/write app data.
-- Anyone with the deployed URL/public Supabase credentials can potentially modify data.
-- Tighten these policies when Supabase Auth is introduced. Never expose a service-role key.

create table if not exists public.bentos (
  id bigint generated by default as identity primary key,
  name text not null,
  bento_date date not null default current_date,
  comment text,
  image_path text,
  is_favorite boolean not null default false,
  created_at timestamptz not null default now()
);
create table if not exists public.components (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  created_at timestamptz not null default now()
);
create unique index if not exists components_name_lower_uidx on public.components (lower(name));
create table if not exists public.bento_components (
  id bigint generated by default as identity primary key,
  bento_id bigint not null references public.bentos(id) on delete cascade,
  component_id bigint not null references public.components(id),
  created_at timestamptz not null default now(),
  unique (bento_id, component_id)
);
create table if not exists public.bento_ratings (
  id bigint generated by default as identity primary key,
  bento_id bigint not null references public.bentos(id) on delete cascade,
  rater_name text not null,
  rating numeric(2,1) not null check (rating >= 1 and rating <= 5 and rating * 2 = trunc(rating * 2)),
  comment text,
  created_at timestamptz not null default now()
);
create unique index if not exists bento_ratings_bento_rater_lower_uidx on public.bento_ratings (bento_id, lower(rater_name));
create table if not exists public.component_ratings (
  id bigint generated by default as identity primary key,
  bento_component_id bigint not null references public.bento_components(id) on delete cascade,
  rater_name text not null,
  rating numeric(2,1) not null check (rating >= 1 and rating <= 5 and rating * 2 = trunc(rating * 2)),
  comment text,
  created_at timestamptz not null default now()
);
create unique index if not exists component_ratings_bc_rater_lower_uidx on public.component_ratings (bento_component_id, lower(rater_name));
create index if not exists bento_components_bento_idx on public.bento_components(bento_id);
create index if not exists bento_ratings_bento_idx on public.bento_ratings(bento_id);
create index if not exists component_ratings_bc_idx on public.component_ratings(bento_component_id);

alter table public.bentos enable row level security;
alter table public.components enable row level security;
alter table public.bento_components enable row level security;
alter table public.bento_ratings enable row level security;
alter table public.component_ratings enable row level security;

do $$ begin
  create policy "prototype anon select bentos" on public.bentos for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "prototype anon insert bentos" on public.bentos for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "prototype anon update bentos" on public.bentos for update to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "prototype anon select components" on public.components for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "prototype anon insert components" on public.components for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "prototype anon select bento_components" on public.bento_components for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "prototype anon insert bento_components" on public.bento_components for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "prototype anon select bento_ratings" on public.bento_ratings for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "prototype anon insert bento_ratings" on public.bento_ratings for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "prototype anon update bento_ratings" on public.bento_ratings for update to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "prototype anon select component_ratings" on public.component_ratings for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "prototype anon insert component_ratings" on public.component_ratings for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "prototype anon update component_ratings" on public.component_ratings for update to anon using (true) with check (true);
exception when duplicate_object then null; end $$;

grant usage on schema public to anon;
grant select, insert, update on public.bentos to anon;
grant select, insert on public.components, public.bento_components to anon;
grant select, insert, update on public.bento_ratings, public.component_ratings to anon;
grant usage, select on all sequences in schema public to anon;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('bento-images','bento-images',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=true, file_size_limit=5242880, allowed_mime_types=array['image/jpeg','image/png','image/webp'];

do $$ begin
  create policy "prototype public read bento images" on storage.objects for select to public using (bucket_id='bento-images');
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "prototype anon upload bento images" on storage.objects for insert to anon with check (bucket_id='bento-images');
exception when duplicate_object then null; end $$;

-- Idempotent seed data.
insert into public.components(name) values ('Tamagoyaki') on conflict do nothing;
insert into public.components(name) values ('Ris') on conflict do nothing;
insert into public.components(name) values ('Teriyaki chicken') on conflict do nothing;
insert into public.bentos(name,bento_date,comment)
select 'Første Bento', current_date, 'Velkommen til Hobby Bento 🍙'
where not exists (select 1 from public.bentos where name='Første Bento' and comment='Velkommen til Hobby Bento 🍙');
insert into public.bento_components(bento_id,component_id)
select b.id,c.id from public.bentos b cross join public.components c
where b.name='Første Bento' and b.comment='Velkommen til Hobby Bento 🍙' and c.name in ('Tamagoyaki','Ris','Teriyaki chicken')
on conflict do nothing;
